stages: 
    - build
    - deploy


build-backend:
    image: golang:1.18
 
    stage: build

    script:
        - cd backend
        - mkdir -p serverbin/
        - go build -o serverbin/server ./src/main.go
  
    artifacts:
        name: server
        paths:
            - backend/serverbin/server

build-frontend:  
    image: node:16

    stage: build

    script:
        - cd frontend
        - npm install
        - npm run check
        - npm run build

    artifacts:
        name: app
        paths:
            - frontend/dist/


deploy-job-test:   
    stage: deploy 
    environment: production
    allow_failure: false
    when: manual
    dependencies:
        - build-backend
        - build-frontend
    
    image: alpine

    before_script:
        - apk add openssh-client
        - eval $(ssh-agent -s)
        - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
    script:
        - scp -r -o StrictHostKeyChecking=no frontend/dist $SSH_USER@$SSH_SERVER:/root/test
