stages: 
    - build
    - deploy

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

build-backend:
    image: golang:1.18
 
    stage: build

    script:
        - cd backend
        - mkdir -p serverbin/
        - go build -o serverbin/go-fiber-server ./src/main.go
  
    artifacts:
        name: server
        paths:
            - backend/serverbin/go-fiber-server

build-frontend:  
    image: node:16

    stage: build

    script:
        - cd frontend
        - echo $VITE_APIENDPOINT >> .env
        - echo $VITE_DOCKERENDPOINT >> .env
        - echo $VITE_WEBSOCKETATTACH >> .env
        - npm install
        - npm run check
        - npm run build

    artifacts:
        name: app
        paths:
            - frontend/dist/


deploy-job-test:   
    stage: deploy 
    environment: production
    allow_failure: false
    dependencies:
        - build-backend
        - build-frontend
    
    image: alpine

    before_script:
        - apk add openssh-client
        - eval $(ssh-agent -s)
        - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
    script:
        - echo "=Deploying Frontend="
        - echo "Removing Old Static Web Content"
        - ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_SERVER "rm -rf /var/www/tutor.chistole.ch/*";
        - echo "Adding New Static Web Content"
        - scp -r -o StrictHostKeyChecking=no frontend/dist $SSH_USER@$SSH_SERVER:/var/www/tutor.chistole.ch/
        - echo "Adjusting File Permissions"
        - ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_SERVER "chown -R www-data:www-data /var/www/tutor.chistole.ch/*";
        - echo "=Deploying Backend="
        - echo "Creating Server .env File"
        - echo PORT=$PORT >> .env
        - echo CERTPATH=$CERTPATH >> .env
        - echo CERTKEYPATH=$CERTKEYPATH >> .env
        - echo "Removing Old Server Binary"
        - ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_SERVER "shopt -s extglob; rm -v /root/server/!(*.log); shopt -u extglob;";
        - echo "Adding New Server Binary"
        - scp -r -o StrictHostKeyChecking=no .env backend/serverbin/go-fiber-server $SSH_USER@$SSH_SERVER:/root/server/
        - echo "Making Binary Executable"
        - ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_SERVER "chmod + x /root/server/go-fiber-server";
        - echo "Killing Current Server Process" Binary Executable"
        - ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_SERVER "pkill go-fiber-server";
        - echo "Starting New Server Process" Binary Executable"
        - ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_SERVER "cd /root/server; ./go-fiber-server >> server.log &; disown -h %1;";
        - echo "Deployment Complete!"

